### ISSUE TITLE
Default value for Model.ListField does not get set

### ISSUE THREAD

**Issue by fernandovalera** [gameboy86/matchbox-orm#16]
I have ran into an issue where I set the 'default' param for the subclass of a Model object to be an empty list, however it does not get set when I create a new object of that subclass with no params.

Default values should be filled into the field so that they can be used right away, before new model objects are even saved.

**Comment by gameboy86** [comment]
Hi, thanks for issue. I have been publish version 0.2.2 witch fix this bug. Please let me know if everything is ok

**Comment by fernandovalera** [comment]
This solved my problem, thank you. I have another issue which I will bring
up and add a branch for...

<http://www.avg.com/email-signature?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
Virus-free.
www.avg.com
<http://www.avg.com/email-signature?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>
