### ISSUE TITLE
ReferenceField does not return a proper DocumentReference db value

### ISSUE THREAD

**Issue by fernandovalera** [gameboy86/matchbox-orm#18]
I noticed that ReferenceField.db_value no longer returns any value, where it previously returned a DocumentReference object.

I have needed to do something like this in order to filter by reference:
```python
class ReferenceField(Field):
...
    def db_value(self, value):
        ...
        return google.cloud.firestore_v1.document.DocumentReference(
            value.collection_name(), value.id, client=db.conn
        )
...
```

This has allowed me to filter by reference with a full collection name (which I currently hack fix a certain sub-collection)

**Comment by gameboy86** [comment]
hi, i have merged your pull request and published version 0.2.3 at pypi. Thanks for your work :-)
