### ISSUE TITLE
startAt() and startAfter() support

### ISSUE THREAD

**Issue by jwitos** [gameboy86/matchbox-orm#26]
Hi, do you have any plans to support `startAt()`, `endAt()`, `startAfter()` [query cursors](https://firebase.google.com/docs/firestore/query-data/query-cursors) or have a workaround to do pagination of the results? Thanks!

**Comment by gameboy86** [comment]
Hi pleas look at pull request [paginator pull request](https://github.com/gameboy86/matchbox-orm/pull/27) where i add suport for Paginate

**Comment by jwitos** [comment]
Thanks, @gameboy86, looks like it's working! I will give it a try deeper this week. I tested it initially and I am able to paginate.

**Comment by gameboy86** [comment]
OK. Please give me know when you finish tests, and  if every thing will be fine, i will publish new version in pypi
