### ISSUE TITLE
Inheritance of abstract model

### ISSUE THREAD

**Issue by catforest** [gameboy86/matchbox-orm#9]
Hello,

 I tried an inheritance of abstract model, but it seemed like it failed.

 My code is attached below. When executing it, it's only "systemNumber" and "systemName" which have proper values on the Firestore. The fields of "createdAt" and "createdBy" from "Suffix_fsm" don't appear there.

	from matchbox import models as fsm, database
	from datetime import datetime
	database.db_initialization('xxx.json')

	class Suffix_fsm(fsm.Model):
	    createdAt = fsm.TimeStampField()
	    createdBy = fsm.TextField(max_length=30, default='')

	    class Meta:
	        abstract = True

	class SystemMaster(Suffix_fsm):
	    systemNumber = fsm.IDField()
	    systemName = fsm.TextField(max_length=50, default='')

	master = SystemMaster(
	    systemNumber=1,
	    systemName='name',
	    createdAt=datetime.now(),
	    createdBy='test',
	)
	master.save()

 It would be great if this issue is resolved.

Thank you !

**Comment by gameboy86** [comment]
Hi catforest, I'll take a look at it and give you an answer. BTW abstract = True is not supported, but i will try to add it asap.

**Comment by catforest** [comment]
Hi gameboy86, thank you for your comment.

> BTW abstract = True is not supported, but i will try to add it asap.

All right. I'm just waiting. Thank you!

**Comment by gameboy86** [comment]
Hi catforest, it is done. Now your example will work, but you must realize that for now you can't specify yout own IDField. At the end of README you will find your example in correct way.
